# Generated by Django 4.0.6 on 2022-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=200)),
                ('mahsulot_tarkibi', models.TextField()),
                ('mahsulot_rasmi', models.ImageField(upload_to='images/')),
                ('mahsulot_narxi', models.CharField(max_length=10)),
            ],
        ),
    ]
